# Form implementation generated from reading ui file './ui/artist_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ArtistDialog(object):
    def setupUi(self, ArtistDialog):
        ArtistDialog.setObjectName("ArtistDialog")
        ArtistDialog.resize(400, 350)
        self.verticalLayout = QtWidgets.QVBoxLayout(ArtistDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_artists = QtWidgets.QListWidget(parent=ArtistDialog)
        self.listWidget_artists.setAlternatingRowColors(True)
        self.listWidget_artists.setObjectName("listWidget_artists")
        self.verticalLayout.addWidget(self.listWidget_artists)
        self.horizontalLayout_Input = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Input.setObjectName("horizontalLayout_Input")
        self.label = QtWidgets.QLabel(parent=ArtistDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_Input.addWidget(self.label)
        self.edit_artist_name = QtWidgets.QLineEdit(parent=ArtistDialog)
        self.edit_artist_name.setObjectName("edit_artist_name")
        self.horizontalLayout_Input.addWidget(self.edit_artist_name)
        self.verticalLayout.addLayout(self.horizontalLayout_Input)
        self.horizontalLayout_Buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Buttons.setObjectName("horizontalLayout_Buttons")
        self.btn_add = QtWidgets.QPushButton(parent=ArtistDialog)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_Buttons.addWidget(self.btn_add)
        self.btn_update = QtWidgets.QPushButton(parent=ArtistDialog)
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout_Buttons.addWidget(self.btn_update)
        self.btn_delete = QtWidgets.QPushButton(parent=ArtistDialog)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_Buttons.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_Buttons)
        self.line = QtWidgets.QFrame(parent=ArtistDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_Close = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Close.setObjectName("horizontalLayout_Close")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Close.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=ArtistDialog)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_Close.addWidget(self.btn_close)
        self.verticalLayout.addLayout(self.horizontalLayout_Close)

        self.retranslateUi(ArtistDialog)
        QtCore.QMetaObject.connectSlotsByName(ArtistDialog)

    def retranslateUi(self, ArtistDialog):
        _translate = QtCore.QCoreApplication.translate
        ArtistDialog.setWindowTitle(_translate("ArtistDialog", "Управление исполнителями"))
        self.label.setText(_translate("ArtistDialog", "Имя исполнителя:"))
        self.edit_artist_name.setPlaceholderText(_translate("ArtistDialog", "Введите имя..."))
        self.btn_add.setText(_translate("ArtistDialog", "Добавить"))
        self.btn_update.setText(_translate("ArtistDialog", "Обновить"))
        self.btn_delete.setText(_translate("ArtistDialog", "Удалить"))
        self.btn_close.setText(_translate("ArtistDialog", "Закрыть"))
